"""initial create tables

Revision ID: ab79d7d6e1c8
Revises: 
Create Date: 2023-10-28 16:12:14.798458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab79d7d6e1c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_no', sa.Integer(), nullable=True),
    sa.Column('station_code', sa.String(), nullable=False),
    sa.Column('station_description', sa.String(), nullable=True),
    sa.Column('ActionLevel', sa.Float(), nullable=True),
    sa.Column('ActionLevelUnits', sa.String(), nullable=True),
    sa.Column('MinorLevel', sa.Float(), nullable=True),
    sa.Column('MinorLevelUnits', sa.String(), nullable=True),
    sa.Column('ModerateLevel', sa.Float(), nullable=True),
    sa.Column('ModerateLevelUnits', sa.String(), nullable=True),
    sa.Column('MajorLevel', sa.Float(), nullable=True),
    sa.Column('MajorLevelUnits', sa.String(), nullable=True),
    sa.Column('ActionFlow', sa.Float(), nullable=True),
    sa.Column('ActionFlowUnits', sa.String(), nullable=True),
    sa.Column('MinorFlow', sa.Float(), nullable=True),
    sa.Column('MinorFlowUnits', sa.String(), nullable=True),
    sa.Column('ModerateFlow', sa.Float(), nullable=True),
    sa.Column('ModerateFlowUnits', sa.String(), nullable=True),
    sa.Column('MajorFlow', sa.Float(), nullable=True),
    sa.Column('MajorFlowUnits', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_code')
    )
    op.create_table('water_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(), nullable=False),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('observed_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('water_category', sa.String(), nullable=True),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('water_level_units', sa.String(), nullable=True),
    sa.Column('water_flow', sa.Float(), nullable=True),
    sa.Column('water_flow_units', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_report')
    op.drop_table('station')
    # ### end Alembic commands ###
